name: suite2p
dependencies:
  - python>3.5
  - pip
  - mkl-fft
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - scikit-learn
  - pip:
    - natsort
    - scanimage-tiff-reader
    - rastermap==0.1.0
    - suite2p
